In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [3]:
df = pd.read_csv(r"E:\study materials\python\py-master\ML\4_save_model\homeprices.csv")
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [5]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [6]:
model.coef_

array([135.78767123])

In [7]:
model.intercept_

180616.43835616432

In [10]:
model.predict([[5000]])

D:\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [12]:
import pickle

In [14]:
with open('model_pickle','wb')as f:
    pickle.dump(model,f)

In [15]:
with open('model_pickle','rb')as f:
    mp = pickle.load(f)

In [17]:
mp.predict([[5000]])

D:\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [23]:
import joblib

In [24]:
joblib.dump(model,'model_joblib')

['model_joblib']

In [25]:
mj = joblib.load('model_joblib')

In [26]:
mj.predict([[5000]])

D:\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])