# 02-Basics of Numpy

#### Creating an array

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
b = np.array([[9.0,8.0,7.0],[1.0,2.0,3.0]])
b

array([[9., 8., 7.],
       [1., 2., 3.]])

Here a is an one dimensional array and b is a two dimensional array.

#### To get the dimension of a numpy array

In [4]:
a = np.array([1,2,3])
a.ndim

1

In [5]:
b = np.array([[9.0,8.0,7.0],[1.0,2.0,3.0]])
b.ndim

2

#### To get the shape of a numpy array

In [6]:
a = np.array([1,2,3])
a.shape

(3,)

In [7]:
b = np.array([[9.0,8.0,7.0],[1.0,2.0,3.0]])
b.shape

(2, 3)

Here (2,3) represents 2 rows and 3 columns.

#### To get the data type of a numpy array

In [8]:
a = np.array([1,2,3])
a.dtype

dtype('int32')

In [9]:
b = np.array([[9.0,8.0,7.0],[1.0,2.0,3.0]])
b.dtype

dtype('float64')

### To assign a data type manually to a numpy array

In [10]:
a = np.array([1,2,3],dtype='int16')
a.dtype

dtype('int16')

In [11]:
b = np.array([[9.0,8.0,7.0],[1.0,2.0,3.0]],dtype='int8')
b.dtype

dtype('int8')

In [12]:
b

array([[9, 8, 7],
       [1, 2, 3]], dtype=int8)

Here we have changed the data type of b to int8 that is why the float value is converted into int value

#### To find the itemsize i.e., length of one array element in bytes

In [13]:
a = np.array([1,2,3])
a.itemsize

4

In [14]:
b = np.array([[9.0,8.0,7.0],[1.0,2.0,3.0]])
b.itemsize

8

### To get the total size of a numpy array

In [15]:
a = np.array([1,2,3])
a.nbytes

12

In [16]:
b = np.array([[9.0,8.0,7.0],[1.0,2.0,3.0]])
b.nbytes

48