# 03-Accessing and changing specific elements, rows, columns, etc

In [1]:
import numpy as np

#### To get the shape of an array

In [2]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a.shape)

(2, 7)


#### To get a specific element inside an array

In [3]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a[1,5])
print(a[1,-2])

13
13


Note  : The indexing will start as 0 not as 1

#### To get a specific row


In [4]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a[0,:])

[1 2 3 4 5 6 7]


#### To get a specific column

In [5]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a[0:,2])

[ 3 10]


#### To get a range of elements

In [6]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a[0,1:6:2])

[2 4 6]


Here we are printing the entire row starting from index 1 to 6 with a stepsize of 2.

[row,column] = [(start:stop:step),(start:stop:step)]

#### To change values inside an array

In [7]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a[:,5] = 20
print(a)

[[ 1  2  3  4  5 20  7]
 [ 8  9 10 11 12 20 14]]


Here we changed the entire 5th(counted from zero)column value to 20.

In [8]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 13 14]]


Here we changed the entire 2nd(counted from zero) column to 1 and 2.

### 3 dimensional array

In [9]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#### To get a specific element inside a 3d array

For easy indexing work outside in

In [10]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b[0,1,1])
print(b[:,1,:])

4
[[3 4]
 [7 8]]


#### To replace an element in an array

In [11]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]
