# 04-Initializing different types of arrays

In [1]:
import numpy as np

#### To print all zero matrix

In [2]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [3]:
b = np.zeros((2,3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
c = np.zeros((2,3,4))
c

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

#### To print all ones matrix

In [5]:
a = np.ones((2,3,4))
a

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

#### To print any number

In [6]:
a = np.full((3,3),99.99)
a

array([[99.99, 99.99, 99.99],
       [99.99, 99.99, 99.99],
       [99.99, 99.99, 99.99]])

###### To change the data type

In [7]:
a = np.full((3,3),99.99,dtype='int8')
a

array([[99, 99, 99],
       [99, 99, 99],
       [99, 99, 99]], dtype=int8)

#### To print an array using a reference array

In [8]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
b = np.full_like(a,4)
print(a)
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[4 4 4 4 4]
 [4 4 4 4 4]]


In [9]:
c = np.full(a.shape,4)
c

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

#### To print a random decimal number (float value)

In [10]:
b = np.random.rand(4,2)
b

array([[0.04215388, 0.57141014],
       [0.08698555, 0.53201977],
       [0.13380337, 0.78317158],
       [0.65095184, 0.69882745]])

##### Printing using a reference array

In [11]:
c = np.random.random_sample(a.shape)
print(c)

[[0.71333647 0.02100651 0.48727602 0.86565397 0.6007694 ]
 [0.22779535 0.81706109 0.22552557 0.47607434 0.91857527]]


#### To print a  random integer 

In [12]:
b = np.random.randint(7)
print(b)

5


In [13]:
c = np.random.randint(7,size=(3,3))
print(c)

[[2 6 6]
 [3 3 6]
 [0 0 5]]


In [14]:
d = np.random.randint(4,7,size=(3,3))
print(d)

[[5 6 5]
 [5 6 6]
 [6 5 4]]


Here we are giving the range of values that needs to be inserted inside the matrix. Here the value 7 is exclusive that's why it's not inside the matrix

#### To print an identity matrix

In [15]:
a = np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

###### To change the dtype

In [16]:
a = np.identity(3,dtype='int8')
a

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

#### To repeat an array

##### To repeat the array in the row

In [17]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


##### To repeat the array in the column

In [18]:
r2 = np.repeat(arr,4,axis=1)
print(r2)

[[1 1 1 1 2 2 2 2 3 3 3 3]]


#### To print a pattern using numpy

1 1 1 1 1 <br>
1 0 0 0 1 <br>
1 0 9 0 1 <br>
1 0 0 0 1 <br>
1 1 1 1 1 

In [19]:
a = np.ones((5,5),dtype='int8')
b = np.zeros((3,3),dtype='int8')
a[1:4,1:4] = b
a[2,2] = 9
a

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

#### Copying an array

In [20]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(a)

[100   2   3]


Here the value of (a) also changed while trying to change b.

In [21]:
z = np.array([1,2,3])
x = z.copy()
x[0] = 100
print(z)
print(x)

[1 2 3]
[100   2   3]
