# 05-Mathematics using numpy

In [1]:
import numpy as np
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

### Basic arithmetic operators

#### addition

In [2]:
b = a+2
b

array([3, 4, 5, 6])

#### subtraction

In [3]:
c = a-2
c

array([-1,  0,  1,  2])

#### multiplication

In [4]:
d = a*2
d

array([2, 4, 6, 8])

#### division

In [5]:
e = a/2
e

array([0.5, 1. , 1.5, 2. ])

#### square

In [6]:
g = a**2
g

array([ 1,  4,  9, 16], dtype=int32)

#### matrix addition

In [7]:
a = np.array([1,2,3,4])
b = np.array([1,0,1,0])
c = a+b
c

array([2, 2, 4, 4])

#### to find the sin value

In [8]:
a = np.array([1,2,3,4])
z = np.sin(a)
z

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

### Linear Algebra

#### matrix multiplication

In [9]:
a = np.ones((2,3))
b = np.full((3,2),2)
z = np.matmul(a,b)
z

array([[6., 6.],
       [6., 6.]])

#### To find the determinant

In [10]:
c = np.identity(3)
x = np.linalg.det(c)
x

1.0

### Statistics

In [11]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

#### min

In [12]:
np.min(a)

1

In [13]:
np.min(a,axis=1)

array([1, 4])

In [14]:
np.min(a,axis=0)

array([1, 2, 3])

#### max

In [15]:
np.max(a)

6

In [16]:
np.max(a,axis=1)

array([3, 6])

In [17]:
np.max(a,axis=0)

array([4, 5, 6])

#### Sum

In [18]:
np.sum(a)

21

In [19]:
np.sum(a,axis=1)

array([ 6, 15])

In [20]:
np.sum(a,axis=0)

array([5, 7, 9])

Here axis 1 represents rows and 0 represents columns