# 06-Reorganizing Arrays

In [1]:
import numpy as np

### Reshaping array

In [2]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
print(before.shape)
after = before.reshape((8,1))
print(after)
print(after.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
(8, 1)


### Vertical stacking

In [3]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
z = np.vstack([v1,v2])
print(z)

[[1 2 3 4]
 [5 6 7 8]]


In [4]:
x = np.vstack([v1,v2,v1,v2])
print(x)

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]


### Horizontal stacking

In [5]:
h1 = np.ones((2,4),dtype='int8')
h2 = np.zeros((2,2),dtype='int8')
x = np.hstack((h1,h2))
x

array([[1, 1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0, 0]], dtype=int8)